[general]
dataset_path = "/home/lxt/EyesNet/dataset/crystal_graph"
learning_rate = 1e-4
padding_len = 500 # max number of atoms in our dataset
batch_size = 1
num_epochs = 10
cuda_device = 1

[xrd_encoder]
block_size = 3501
patch_size = 16  # Number of bytes per patch
n_embd = 256      # Embedding dimension
n_head = 2        # Number of attention heads
n_layers_encoder = 2  # lE << lG # Number of layers in the encoder
n_layers_latent = 4   # lG # Number of layers in the latent transformer
dropout = 0.1
vocab_size = 10000  # Number of unique bytes
hash_sizes = [3, 4, 5, 6]  # n-gram sizes
hash_table_size = 500  # Size of each hash table


[crystal_encoder]
dim = 256
max_degree = 2
# max_neighbors = 12
depth = 2
heads = 2
dim_head = 32
dim_edge_refinement = 256
num_atoms = 500
return_coors = false
cutoff_radius = 5


[projection]
hidden_dim = 128
dropout = 0.1