[general]
dataset_path = "/home/lxt/EyesNet/dataset/crystal_graph"
learning_rate = 1e-4
batch_size = 8
num_epochs = 400
weight_decay = 1e-4
warmup_epochs = 10
patience = 10
cuda_device = 1

[xrd_encoder]
block_size = 3501
patch_size = 16           # Number of bytes per patch
n_embd = 256              # Embedding dimension
n_head = 8                # Number of attention heads
n_layers_encoder = 2      # lE << lG # Number of layers in the encoder
n_layers_latent = 4       # lG # Number of layers in the latent transformer
dropout = 0.3
vocab_size = 10001        # Number of unique bytes
hash_sizes = [3, 4, 5, 6] # n-gram sizes
hash_table_size = 500     # Size of each hash table


[crystal_encoder]
# official
n_atom_basis = 256
n_interactions = 8
radial_basis = "BesselBasis"
n_rbf = 20
cutoff = 5.0
max_z = 100
epsilon = 1e-8
max_num_neighbors = 32
num_heads = 8
attn_dropout = 0.3
edge_updates = true
scale_edge = true
lmax = 2
aggr = "add"
sep_int_vec = true

[projection]
hidden_dim = 128
dropout = 0.3
